version: '3.7'
services:

  # Environment
  bank-db:
    image: postgres
    hostname: bank-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword

  test-bank-db:
    image: postgres
    hostname: test-bank-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword



#  test_db:
#    container_name: test_bank_db
#    image: library/postgres:${POSTGRES_VERSION}
#
#    environment:
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_DB=test_bank
#      - PGDATA=/var/lib/postgresql/data/test_bank
#    ports:
#      - 5434:5432

