server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        .id: test
        .uri: lb://authorization
        predicates:
          - Path=/test
#          - Method=GET